modLoader="javafml" 

loaderVersion="${loader_version_range}" 

license="${mod_license}"

[[mods]] 

modId="neofactories" 

version="1.0.0" 

displayName="NeoFactories" 

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" 

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" 

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" 

# A text field displayed in the mod UI
#credits="" 

authors="mogu6321,minorinrin" 

description='''${mod_description}'''

[[dependencies.neofactories]] 
   
    modId="neoforge" 
    
    type="required" 
    
    versionRange="${neo_version_range}" 
   
    ordering="NONE"

    side="BOTH"


[[dependencies.neofactories]]
    modId="minecraft"
    type="required"
    
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

